# Generated by Django 5.1.6 on 2025-05-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            # field=models.CharField(default='000-0000000000', max_length=20, unique=True),
            field=models.CharField(max_length=20, unique=True, null=True, blank=True),

        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
