# Generated by Django 5.2.1 on 2025-05-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_orderitem_price_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
