# Generated by Django 5.2.1 on 2025-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='No description available.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
