# Generated by Django 5.2.1 on 2025-05-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_description_book_pages_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('interests', models.TextField()),
                ('favorite_books', models.ManyToManyField(related_name='favorites', to='books.book')),
            ],
        ),
    ]
