# Generated by Django 5.2.1 on 2025-05-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_bookplan_bookrecommendation_bookreview_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPlan',
        ),
        migrations.DeleteModel(
            name='BookRecommendation',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
