# Generated by Django 5.2.1 on 2025-05-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_delete_bookplan_delete_bookrecommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
