# Generated by Django 5.2.1 on 2025-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covers/', verbose_name='Muqova Rasmi')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Janr')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan Vaqt')),
            ],
        ),
    ]
